# Generated by Django 4.2.5 on 2023-10-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
