# Generated by Django 4.2.5 on 2023-10-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0003_rename_stock_predicted_price_stock_stock_predicted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock_name',
            new_name='stock_ticker',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_predicted',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_close_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_prediction',
            field=models.BooleanField(default=False),
        ),
    ]
